language: python

python:
  - 2.7

branches:
  only:
    - master

install:
  - pip install 'distribute>=0.6.34'
  - pip install -e . --use-mirrors
  - pip install -r reqs/travis.txt --use-mirrors

script:
  - nosetests
